# PowerShell Script to Auto-Generate sitemap.xml from HTML files
# Run this script whenever you add new pages to automatically update sitemap.xml

$domain = "https://seoconsultantsrilanka.com"
$outputPath = ".\assets\sitemap.xml"
$currentDate = (Get-Date).ToString("yyyy-MM-ddTHH:mm:sszzz")

# Get all HTML files in the current directory, excluding non-public/partial files
$exclude = @(
    'header-component.html',
    'navbar-component.html',
    '403.html','404.html','500.html'
)
$htmlFiles = Get-ChildItem -Path "." -Filter "*.html" |
    Where-Object { $exclude -notcontains $_.Name } |
    Sort-Object Name

# Define priority based on page importance
function Get-Priority {
    param($fileName)
    
    $highPriority = @("index.html")
    $mediumPriority = @("about.html", "contact.html", "services.html", "pricing.html", "faq.html", "blog.html")
    
    if ($highPriority -contains $fileName) {
        return "1.00"
    } elseif ($mediumPriority -contains $fileName) {
        return "0.80"
    } else {
        return "0.64"
    }
}

# Start building XML content
$xmlContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- Auto-generated by update-sitemap.ps1 -->

"@

# Process each HTML file
foreach ($file in $htmlFiles) {
    $fileName = $file.Name
    $lastModified = $file.LastWriteTime.ToString("yyyy-MM-ddTHH:mm:sszzz")
    $priority = Get-Priority -fileName $fileName
    
    # Convert filename to URL path (remove .html extension)
    if ($fileName -eq "index.html") {
        $urlPath = "/"
    } else {
        $urlPath = "/" + $fileName.Replace(".html", "").Replace(" ", "%20")
    }
    
    # Add URL entry
    $xmlContent += @"
<url>
  <loc>$domain$urlPath</loc>
  <lastmod>$lastModified</lastmod>
  <priority>$priority</priority>
</url>

"@
}

# Close the XML
$xmlContent += @"
</urlset>
"@

# Write to file
Set-Content -Path $outputPath -Value $xmlContent -Encoding UTF8

Write-Host "Sitemap generated successfully at: $outputPath"
Write-Host "Total pages: $($htmlFiles.Count)"
Write-Host "Last updated: $currentDate"
Write-Host ""
Write-Host "Sitemap includes:"
foreach ($file in $htmlFiles) {
    $urlPath = if ($file.Name -eq "index.html") { "/" } else { "/" + $file.Name.Replace(".html", "") }
    $fullUrl = $domain + $urlPath
    Write-Host "  - $fullUrl"
}
